### ISSUE TITLE
Error in the sendTradeOffer Function

### ISSUE THREAD

**Issue by Rulzius** [Koncealed/node-steam-trade-farms#19]
**### FIXED IF YOU HAVE SAME PROBLEM AND USING ARCHISTEAMFARM DISABLE AUTO GIFT,TRADE ACCEPT**

[ACCOUNT LOGIN] Error in the sendTradeOffer Function
[ACCOUNT LOGIN
![Capture](https://user-images.githubusercontent.com/75549225/117838561-8070b380-b28b-11eb-8a5e-111a580b91cc.PNG)
] Error: There was an error accepting this trade offer.  Please try again later. (11)
(node:15441) UnhandledPromiseRejectionWarning: Error: There was an error accepting this trade offer.  Please try again later. (11)
    at Object.exports.makeAnError (/root/node-steam-trade-farm-master/node_modules/steam-tradeoffer-manager/lib/helpers.js:17:12)
    at SteamCommunity.<anonymous> (/root/node-steam-trade-farm-master/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:485:13)
    at Request._callback (/root/node-steam-trade-farm-master/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/root/node-steam-trade-farm-master/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/root/node-steam-trade-farm-master/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/root/node-steam-trade-farm-master/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15441) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**I'M USING Ubuntu 18.04 Server**
![Capture2](https://user-images.githubusercontent.com/75549225/117839215-1278bc00-b28c-11eb-93c3-df6c4c58aa11.PNG)

**Comment by RobertSkonieczny** [comment]
I see you are trying to run this on this on a linux server. I never tested that before. The one thing that I did note is that you need to be logged into the main account on steam while the bot is running. Try making the MAX_RETRIES to 10. Let's see if that does anything.

Thanks!

**Comment by Rulzius** [comment]
I'm sorry i forgot i was boosting hours with ArchiSteamFarm and i had enabled auto trade accept option thats why i had problems with tradefarm So far everything works great
